## NumPy
- Numerical Python 
- NumPy merupakan sebuah vektor
- Array yang isinya angka, mirip List tapi isinya angka semua 
- isi NumPynya harus sama jumlahnya 

In [2]:
import numpy as np

In [4]:
[1,2,3,4]

[1, 2, 3, 4]

NumPy 1 dimensi

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

NumPy 2 dimensi

In [6]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
a.ndim #untuk mencari tahu dimensi NumPy

2

In [12]:
a.shape #untuk mencari tahu ukuran NumPy

(3, 3)

NumPy 3 dimensi

In [3]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [19]:
#penjabaran, harus sama jumlahnya
b = np.array(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]],
        [[9,10],[,12]]
    ]
)

SyntaxError: invalid syntax (1404736709.py, line 6)

In [31]:
b

NameError: name 'b' is not defined

In [15]:
b.ndim

3

In [16]:
b.shape

(3, 2, 2)

# Array
- np.array()    #menulis numpy
- np.zeros()    #isinya 0 semua
- np.ones()     #isinya 1 semua
- np.empty()    #isinya random
- np.arange()   #range 

In [ ]:
help(np.array)

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in

In [9]:
np.empty(6)

array([0.00000000e+000, 1.90616412e-026, 6.26160360e-312, 6.26160360e-312,
       4.94065646e-323, 1.87744945e-322])

In [10]:
np.empty((5,1))

array([[1.90616412e-026],
       [6.26160360e-312],
       [6.26160360e-312],
       [4.94065646e-323],
       [1.87744945e-322]])

In [11]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [14]:
np.arange(5,10,2) #sama kaya range 

array([5, 7, 9])

## Add, Remove, Sort 
- np.append()       #menambahkan 
- np.delete()       #menghapus 
- np.sort()         #mengurutkan 

In [5]:
arr = np.arange(8)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
mylist = list(range(8))

In [9]:
mylist.append([1,2])

In [11]:
mylist

[0, 1, 2, 3, 4, 5, 6, 7, [1, 2]]

In [18]:
np.append(arr,[8])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.append(arr,[[1,2,]])

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [13]:
arr
#NumPy sifatnya tidak langsung mengubah isi 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
#bisa berubah jika 
arr2 = np.append(arr,[1,2])

In [17]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2, 1, 2])

In [19]:
arr3 = np.append(arr,[[1,2]])

In [20]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
np.delete(arr,1)

array([0, 2, 3, 4, 5, 6, 7])

In [23]:
np.delete(arr,7)

array([0, 1, 2, 3, 4, 5, 6])

In [25]:
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
print('dim', arr.ndim)
print('size', arr.size) #isi dari numpy arraynya
print('shape', arr.shape)

dim 1
size 8
shape (8,)


In [28]:
help(np.ndarray.ndim)

Help on getset descriptor numpy.ndarray.ndim:

ndim
    Number of array dimensions.
    
    Examples
    --------
    >>> x = np.array([1, 2, 3])
    >>> x.ndim
    1
    >>> y = np.zeros((2, 3, 4))
    >>> y.ndim
    3



In [33]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
print("dim", a.ndim)
print("size", a.size)
print("shape", a.shape)

dim 2
size 9
shape (3, 3)


In [36]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [37]:
print("dim", b.ndim)
print("size", b.size)
print("shape", b.shape)

dim 3
size 12
shape (3, 2, 2)


In [39]:
array_example = np.array([
    [[1,2,3,4],
     [5,6,7,8]],

    [[9,10,11,12],
     [13,14,15,16]],

    [[17,18,19,20],
     [21,22,23,24]],

    [[25,26,27,28],
     [29,30,31,32]]
])

In [40]:
print(array_example)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]]]


In [41]:
print("dim", array_example.ndim)
print("size", array_example.size)
print("shape", array_example.shape)

dim 3
size 32
shape (4, 2, 4)


## Reshape

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
arr.shape

(8,)

In [44]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
arr.reshape(2,4).ndim

2

In [45]:
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [48]:
arr.reshape(4,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]]])

In [49]:
arr.reshape(4,2,1).ndim

3

In [50]:
#calling numpy tidak harus np, tapi bisa diganti yang lain 
import numpy as plastik

In [52]:
plastik.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [54]:
import numpy as np

In [56]:
np.lookfor("equal") #buat mencari function

Search results for 'equal'
--------------------------
numpy.equal
    Return (x1 == x2) element-wise.
numpy.not_equal
    Return (x1 != x2) element-wise.
numpy.less_equal
    Return the truth value of (x1 <= x2) element-wise.
numpy.sinc
    Return the normalized sinc function.
numpy.greater_equal
    Return the truth value of (x1 >= x2) element-wise.
numpy.isclose
    Returns a boolean array where two arrays are element-wise equal within a
numpy.allclose
    Returns True if two arrays are element-wise equal within a tolerance.
numpy.char.equal
    Return (x1 == x2) element-wise.
numpy.ma.equal
    Return (x1 == x2) element-wise.
numpy.issubdtype
    Returns True if first argument is a typecode lower/equal in type hierarchy.
numpy.array_equiv
    Returns True if input arrays are shape consistent and all elements equal.
numpy.ma.allequal
    Return True if all entries of a and b are equal, using
numpy.char.not_equal
    Return (x1 != x2) element-wise.
numpy.array_api.equal
    Array API 

In [57]:
np.lookfor("compare")

Search results for 'compare'
----------------------------
numpy.compare_chararrays
    Performs element-wise comparison of two string arrays using the
numpy.lib._version.NumpyVersion
    Parse and compare numpy version strings.
numpy.ma.MaskedArray._comparison
    Compare self with other using operator.eq or operator.ne.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.sort
    Return a sorted copy of an array.
numpy.equal
    Return (x1 == x2) element-wise.
numpy.testing.assert_array_almost_equal_nulp
    Compare two arrays relatively to their spacing.
numpy.nanmax
    Return the maximum of an array or maximum along an axis, ignoring any
numpy.nanmin
    Return minimum of an array or minimum along an axis, ignoring any NaNs.
numpy.argsort
    Returns the indices that would sort an array.
numpy.isclose
    Returns a boolean array where two arrays are element-wise equal within a
numpy.maximum
    Element-wise maximum of 

## Convert 1D to 2D
- np.newaxis        #menambahkan axis/dimensi diluar atau diawal 
- np.expand_dims    #menambahkan axis/dimensi tapi kita bisa nentuin mau ditaroh dimana 


In [61]:
help(np.newaxis)

Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.



In [62]:
help(np.expand_dims)

Help on _ArrayFunctionDispatcher in module numpy:

expand_dims(a, axis)
    Expand the shape of an array.
    
    Insert a new axis that will appear at the `axis` position in the expanded
    array shape.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int or tuple of ints
        Position in the expanded axes where the new axis (or axes) is placed.
    
        .. deprecated:: 1.13.0
            Passing an axis where ``axis > a.ndim`` will be treated as
            ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will
            be treated as ``axis == 0``. This behavior is deprecated.
    
        .. versionchanged:: 1.18.0
            A tuple of axes is now supported.  Out of range axes as
            described above are now forbidden and raise an `AxisError`.
    
    Returns
    -------
    result : ndarray
        View of `a` with the number of dimensions increased.
    
    See Also
    --------
    squeeze : The inverse operation, r

In [63]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [66]:
arr.ndim

1

In [72]:
arr.shape

(8,)

In [68]:
arr4 = arr[np.newaxis]

In [73]:
arr4

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [70]:
arr4.ndim

2

In [71]:
arr4.shape

(1, 8)

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a.shape

(3, 3)

In [80]:
a2 = np.expand_dims(a, axis=0)

In [81]:
a2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [82]:
a2.shape

(1, 3, 3)

In [83]:
a3 = np.expand_dims(a, axis=1)

In [84]:
a3

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [85]:
a3.shape

(3, 1, 3)

## Indexing dan Slicing 
```
arr[start:stop:step]
```

### Indexing

In [86]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [88]:
arr[4]

4

In [89]:
arr[0]

0

In [90]:
arr[4:]

array([4, 5, 6, 7])

### Slicing

In [91]:
arr > 2

array([False, False, False,  True,  True,  True,  True,  True])

In [92]:
arr[arr>2]

array([3, 4, 5, 6, 7])

In [93]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
a[a < 5].shape

(4,)

In [98]:
a % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [99]:
a[a%2==0]

array([2, 4, 6, 8])

In [100]:
a % 3 == 0

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [102]:
a[(a % 2 == 0)&(a % 3 ==0)] #digabung 

array([6])

## Creating from Existing Data 
```
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()
```

In [10]:
arr

NameError: name 'arr' is not defined

In [105]:
arr5 = arr[3:8]

In [106]:
arr5

array([3, 4, 5, 6, 7])

In [6]:
a_1 = np.array([[1,1],[2,2]])
a_1

array([[1, 1],
       [2, 2]])

In [18]:
a_3 = np.array([[1,1],[2,2],[3,3]])

In [7]:
a_2 = np.array([[3,3],[4,4]])
a_2

array([[3, 3],
       [4, 4]])

In [14]:
np.vstack([a_1,a_2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [17]:
np.hstack([a_2,a_1])

array([[3, 3, 1, 1],
       [4, 4, 2, 2]])

In [20]:
np.vstack([a_3, a_2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [3, 3],
       [4, 4]])

In [23]:
np.hstack([a_1, a_3]) #karena shapenya beda, kalau horizontal shapenya harus sama 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [29]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                     [13,14,15,16,17,18,19,20,21,22,23,24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [30]:
np.hsplit(arrsplit, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [32]:
np.vsplit(arrsplit, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.vsplit(a, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [36]:
np.hsplit(a,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [37]:
b = a

In [38]:
id(a)

2220192015600

In [39]:
id(b)

2220192015600

In [40]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
b = a.view()

In [43]:
print (id(a))
print (id(b))

2220192015600
2220194472432


In [44]:
a.view()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
c = a.copy()

## Basic Array Operations

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
arr + 1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [51]:
arr[1] + arr [7]

8

In [53]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

## Array Operations 
```
data.max()
data.min()
data.sum()
data.mean()
data.std()
data.var()
```

In [54]:
arr.sum()

28

In [55]:
data = np.array([1,2])
data

array([1, 2])

In [57]:
ones = np.ones([2])
ones

array([1., 1.])

In [58]:
data + ones

array([2., 3.])

In [61]:
data * ones

array([1., 2.])

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [64]:
print(arr.sum())
print(arr.max())
print(arr.min())

28
7
0


In [68]:
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

28
7
0


In [65]:
# method 
# function dianggil melalui object 
# object oriented programming
# lebih ringkas  
"Halo".upper()

'HALO'

In [66]:
# function 
# functional programming 
str.upper("Halo")

'HALO'

# Matrices

In [69]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.random.random((3,2))

array([[0.50660124, 0.25593484],
       [0.81318194, 0.61558399],
       [0.75113051, 0.32185741]])

## Matrix Arithmetic 

In [7]:
data = np.arange(1,5).reshape(2,2)
ones = np.ones((2,2))
ones_row = np.ones((2))

print(data)
print(ones)
print(ones_row)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[1. 1.]


In [77]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [8]:
print(data+ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [9]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array ([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [11]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

In [10]:
np.dot(a_2,a_1)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

## Matrix Indexing

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a[0]

array([1, 2, 3])

In [14]:
a[0][0]

1

In [16]:
a[0][2]

3

In [13]:
a[1]

array([4, 5, 6])

In [17]:
a[1][2]

6

In [22]:
data = np.array([[1,2],[3,4],[5,6]])

print(data)
print(data[0])
print(data[0][1]) #atau
print(data[0,1])
print(data[1])
print(data[1][1]) #atau
print(data[1,1])
print(data[2])
print(data[2][1])
print(data[1:3,0])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
2
2
[3 4]
4
4
[5 6]
6
[3 5]


## Matrix Aggregation

In [23]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [29]:
print(data.max(axis=0))
print(data.max(axis=1))
print(data.min(axis=0))
print(data.min(axis=1))

[5 6]
[2 4 6]
[1 2]
[1 3 5]


In [30]:
print(data.sum(axis=0))
print(data.sum(axis=1))
#axis 0 itu satu kolom, axis 1 itu satu baris

[ 9 12]
[ 3  7 11]


## Transposing

In [31]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [33]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [35]:
data.shape

(3, 2)

In [36]:
data.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [37]:
data.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [38]:
np.arange(15).reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
np.linspace(1,50, num=100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [43]:
np.linspace(0,50,num=20).reshape((5,4))

array([[ 0.        ,  2.63157895,  5.26315789,  7.89473684],
       [10.52631579, 13.15789474, 15.78947368, 18.42105263],
       [21.05263158, 23.68421053, 26.31578947, 28.94736842],
       [31.57894737, 34.21052632, 36.84210526, 39.47368421],
       [42.10526316, 44.73684211, 47.36842105, 50.        ]])

## N Dimensional Array

In [46]:
ndarr = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
ndarr.shape

(2, 2, 2)

In [48]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
randomarr = np.random.random((4,3,2))
print(randomarr)

[[[0.79897443 0.07520859]
  [0.10125833 0.15248578]
  [0.073759   0.93966378]]

 [[0.67199605 0.05675524]
  [0.52116638 0.45555597]
  [0.32800633 0.41706395]]

 [[0.39687189 0.82339768]
  [0.12968558 0.39805523]
  [0.09998642 0.14401394]]

 [[0.49357357 0.80592769]
  [0.02310127 0.33546331]
  [0.38995646 0.00583402]]]


In [53]:
randomarr.reshape(-1)

array([0.79897443, 0.07520859, 0.10125833, 0.15248578, 0.073759  ,
       0.93966378, 0.67199605, 0.05675524, 0.52116638, 0.45555597,
       0.32800633, 0.41706395, 0.39687189, 0.82339768, 0.12968558,
       0.39805523, 0.09998642, 0.14401394, 0.49357357, 0.80592769,
       0.02310127, 0.33546331, 0.38995646, 0.00583402])

In [54]:
randomarr.reshape(randomarr.size)

array([0.79897443, 0.07520859, 0.10125833, 0.15248578, 0.073759  ,
       0.93966378, 0.67199605, 0.05675524, 0.52116638, 0.45555597,
       0.32800633, 0.41706395, 0.39687189, 0.82339768, 0.12968558,
       0.39805523, 0.09998642, 0.14401394, 0.49357357, 0.80592769,
       0.02310127, 0.33546331, 0.38995646, 0.00583402])

## Math Formulas 

In [56]:
np.sqrt(25)

5.0

In [ ]:
#rumus MSE
error = (1/n) * np.sum(np.square(observed-prediction))