## NumPy
- Numerical Python 
- NumPy merupakan sebuah vektor
- Array yang isinya angka, mirip List tapi isinya angka semua 
- isi NumPynya harus sama jumlahnya 

In [2]:
import numpy as np

In [4]:
[1,2,3,4]

[1, 2, 3, 4]

NumPy 1 dimensi

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

NumPy 2 dimensi

In [6]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
a.ndim #untuk mencari tahu dimensi NumPy

2

In [12]:
a.shape #untuk mencari tahu ukuran NumPy

(3, 3)

NumPy 3 dimensi

In [13]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [19]:
#penjabaran, harus sama jumlahnya
b = np.array(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]],
        [[9,10],[,12]]
    ]
)

SyntaxError: invalid syntax (1404736709.py, line 6)

In [14]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [15]:
b.ndim

3

In [16]:
b.shape

(3, 2, 2)

# Array
- np.array()    #menulis numpy
- np.zeros()    #isinya 0 semua
- np.ones()     #isinya 1 semua
- np.empty()    #isinya random
- np.arange()   #range 

In [ ]:
help(np.array)

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in

In [9]:
np.empty(6)

array([0.00000000e+000, 1.90616412e-026, 6.26160360e-312, 6.26160360e-312,
       4.94065646e-323, 1.87744945e-322])

In [10]:
np.empty((5,1))

array([[1.90616412e-026],
       [6.26160360e-312],
       [6.26160360e-312],
       [4.94065646e-323],
       [1.87744945e-322]])

In [11]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [14]:
np.arange(5,10,2) #sama kaya range 

array([5, 7, 9])

## Add, Remove, Sort 
- np.append()       #menambahkan 
- np.delete()       #menghapus 
- np.sort()         #mengurutkan 

In [16]:
arr = np.arange(8)

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
np.append(arr,[8])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])